#!/bin/bash
set -eu

cd "$(dirname "${0}")" || exit 1

svg_in="${1}"
png_out="${2}"
dpi=${3:-96}

# Workaround to support running multiple parallel instances of inkscape:
# https://gitlab.com/inkscape/inkscape/-/issues/4716#note_1898150983
export SELF_CALL=xxx
function inkscape_convert() {
	local in="${1}"
	local out="${2}"
	echo "converting ${in} -> ${out}"
	inkscape --export-area-page --export-overwrite --export-type=png --export-dpi="${dpi}" --export-filename="${out}" "${in}"
}

inkscape_convert "${svg_in}" "${png_out}"
